# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cc1f567571310844e552808d999f68550f00ec02760f2666b79d4d06692fd1b8e02d949f64c68d430adac572d40bd173f1bd5412a2c515024cfd5e04a313cbf

test:
  secret_key_base: fe5645ea684e19afbce5f9abdef57da1bdd96d97fa5b296a3a8da012b0bc5e64e80bc5bda1f572fc2204a55302244d9e683a1da064d3b5723c39062f1b3a813b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
